Notebook tests
mlcommons/modelgauge pull request #379
Opened 2024-04-09 16:40 UTC by bkorycki

This PR sets up some basic automated execution testing of newhelm in python notebooks. It uses the pytest plugin nbmake for notebook execution, which treats each file as an individual test. I chose to keep all of the notebook-related testing in a single file (and therefore a single canonical test) to avoid amassing many few-line test files. 

Another option is to add some markup and move the notebook to the docs as an interactive demo. And then we can still run the automated execution test on it there.

2024-04-09 19:06 UTC, wpietri requested changes
This is a great start.

* We should make sure this is easy to run from the CLI for developers.
* If you're expecting to create more notebook tests, I might create a directory in tests for them now, but if you think one's plenty for now, then this is fine.
* It doesn't work for me, complaining that I need the demo api key in my secrets file. For the automated tests, you should find a way to fix that. Maybe  checking in a secrets.toml somewhere in the tests, or maybe that means faking out the secrets as part of the test running? 

Other than that, looks good to me.

2024-04-11 20:17 UTC, bkorycki commented on .github/workflows/scheduled-tests.yml
> +        pip install nbmake
That makes sense.

2024-04-11 23:19 UTC, wpietri approved these changes

2024-04-12 14:50 UTC, brianwgoldman approved these changes

2024-04-12 16:16 UTC, merged